[tool.poetry]
name = "python"
version = "0.1.0"
description = ""
authors = ["Ruidy"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = {extras = ["all"], version = "^0.85.0"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
